// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vamkwsgjznumyabbdmzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhbWt3c2dqem51bXlhYmJkbXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjc4MTgsImV4cCI6MjA2NDgwMzgxOH0.J9cHww3-I6SYIZoH0frnRdyzri6TxJ77N4KXACNBdbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);